config/routes.rb
Rails.application.routes.draw do
  resources :antrians
  resources :pesans do
  	resources :bls
  end
  resources :diskus do
  	resources :komentars
  end

  resources :diskusis do
  	resources :commentds
  end
  resources :mobils
  resources :orangs
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'orangs#index'

  # ----- add these lines here: -----

	# Add a root route if you don't have one...
	# We can use users#new for now, or replace this with the controller and action you want to be the site root:
	root to: 'users#new'
  	
  	# sign up page with form:
	get 'users/new' => 'users#new', as: :new_user
	
	# create (post) action for when sign up form is submitted:
	post 'users' => 'users#create'

  	# ----- end of added lines -----

  	# ----- add these lines here: -----
	
	# log in page with form:
	get '/login'     => 'sessions#new'
	
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	
	# delete action to log out:
	delete '/logout' => 'sessions#destroy'  
  	
  	# ----- end of added lines -----

  # ----- add these lines here: -----

  # Add a root route if you don't have one...
  # We can use users#new for now, or replace this with the controller and action you want to be the site root:
  #root to: 'users#new'
    
    # sign up page with form:
  get 'bebeks/new' => 'bebeks#new', as: :new_bebek
  
  # create (post) action for when sign up form is submitted:
  post 'bebeks' => 'bebeks#create'

    # ----- end of added lines -----
    # ----- add these lines here: -----
  
  # log in page with form:
  get '/lbebek'     => 'lbebeks#new'
  
  # create (post) action for when log in form is submitted:
  post '/lbebek'    => 'lbebeks#create'
  
  # delete action to log out:
  delete '/logout' => 'lbebeks#destroy'  
    
    # ----- end of added lines -----


end

app/models/antrian.rb
class Antrian < ApplicationRecord
  belongs_to :orang
  belongs_to :user
end

app/models/bala.rb
class Bala < ApplicationRecord
  belongs_to :pesan
end

app/models/bebek.rb
class Bebek < ApplicationRecord
	# ----- add these lines here: -----
	
	#has_secure_password

	# Verify that email field is not blank and that it doesn't already exist in the db (prevents duplicates):
	validates :email, presence: true, uniqueness: true
	
	# ----- end of added lines -----
end

app/models/bl.rb
class Bl < ApplicationRecord
  belongs_to :pesan
end

app/models/commentd.rb
class Commentd < ApplicationRecord
  belongs_to :diskusi
end

app/models/commentdi.rb
class Commentdi < ApplicationRecord
  belongs_to :diskusi
end

app/models/disku.rb
class Disku < ApplicationRecord
  belongs_to :orang
  has_many :komentars
end

app/models/diskusi.rb
class Diskusi < ApplicationRecord
  belongs_to :orangs
  has_many :commentds
end

app/models/komentar.rb
class Komentar < ApplicationRecord
  belongs_to :disku
end

app/models/mobil.rb
class Mobil < ApplicationRecord
  belongs_to :orang
end

app/models/orang.rb
class Orang < ApplicationRecord
# has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
#   validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
has_attached_file :image, :styles => { :small => "150x150>" },
                  :url  => "/assets/orangs/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/orangs/:id/:style/:basename.:extension"

validates_attachment_presence :image
validates_attachment_size :image, :less_than => 5.megabytes
validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
end

app/models/pesan.rb
class Pesan < ApplicationRecord
  belongs_to :orang
  belongs_to :user
  has_many :bls
end

app/models/user.rb
class User < ApplicationRecord
	# ----- add these lines here: -----
	
	has_secure_password

	# Verify that email field is not blank and that it doesn't already exist in the db (prevents duplicates):
	validates :email, presence: true, uniqueness: true
	
	# ----- end of added lines -----
end

app/controllers/mobils_controller.rb
class MobilsController < ApplicationController
  before_action :set_mobil, only: [:show, :edit, :update, :destroy]

  # GET /mobils
  # GET /mobils.json
  def index
    @mobils = Mobil.all
  end

  # GET /mobils/1
  # GET /mobils/1.json
  def show
  end

  # GET /mobils/new
  def new
    @mobil = Mobil.new
  end

  # GET /mobils/1/edit
  def edit
  end

  # POST /mobils
  # POST /mobils.json
  def create
    @mobil = Mobil.new(mobil_params)

    respond_to do |format|
      if @mobil.save
        format.html { redirect_to @mobil, notice: 'Mobil was successfully created.' }
        format.json { render :show, status: :created, location: @mobil }
      else
        format.html { render :new }
        format.json { render json: @mobil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mobils/1
  # PATCH/PUT /mobils/1.json
  def update
    respond_to do |format|
      if @mobil.update(mobil_params)
        format.html { redirect_to @mobil, notice: 'Mobil was successfully updated.' }
        format.json { render :show, status: :ok, location: @mobil }
      else
        format.html { render :edit }
        format.json { render json: @mobil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mobils/1
  # DELETE /mobils/1.json
  def destroy
    @mobil.destroy
    respond_to do |format|
      format.html { redirect_to mobils_url, notice: 'Mobil was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mobil
      @mobil = Mobil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mobil_params
      params.require(:mobil).permit(:nama, :keterangan, :orang_id)
    end
end

app/helpers/bebeks_helper.rb
module BebeksHelper
end

app/helpers/bls_helper.rb
module BlsHelper
end

app/helpers/diskus_helper.rb
module DiskusHelper
end

app/helpers/lbebeks_helper.rb
module LbebeksHelper
end

app/helpers/mobils_helper.rb
module MobilsHelper
end

app/helpers/orangs_helper.rb
module OrangsHelper
end

app/helpers/pesans_helper.rb
module PesansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/mobils/_form.html.erb
<%= form_with(model: mobil, local: true) do |form| %>
  <% if mobil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mobil.errors.count, "error") %> prohibited this mobil from being saved:</h2>

      <ul>
      <% mobil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nama %>
    <%= form.text_field :nama %>
  </div>

  <div class="field">
    <%= form.label :keterangan %>
    <%= form.text_field :keterangan %>
  </div>

  <div class="field">
    <%= form.label :orang_id %>
    <%= current_user.name %>
    <%= form.text_field :orang_id , :value => current_user.id , :type => 'hidden' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mobils/edit.html.erb
<h1>Editing Mobil</h1>

<%= render 'form', mobil: @mobil %>

<%= link_to 'Show', @mobil %> |
<%= link_to 'Back', mobils_path %>

app/views/mobils/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mobils <%= current_user.id %></h1>

<table>
  <thead>
    <tr>
      <th>Nama</th>
      <th>Keterangan</th>
      <th>Orang</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    
    <% @mobils.each do |mobil| %>
      <% if current_user.id == mobil.orang.id %>
      <tr>
        <td><%= mobil.nama %></td>
        <td><%= mobil.keterangan %></td>
        <td><%= mobil.orang.id %></td>
        <td><%= link_to 'Show', mobil %></td>
        <td><%= link_to 'Edit', edit_mobil_path(mobil) %></td>
        <td><%= link_to 'Destroy', mobil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
     <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mobil', new_mobil_path %>

app/views/mobils/new.html.erb
<h1>New Mobil</h1>

<%= render 'form', mobil: @mobil %>

<%= link_to 'Back', mobils_path %>

app/views/mobils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama:</strong>
  <%= @mobil.nama %>
</p>

<p>
  <strong>Keterangan:</strong>
  <%= @mobil.keterangan %>
</p>

<p>
  <strong>Orang:</strong>
  <%= @mobil.orang.nama %>
</p>

<%= link_to 'Edit', edit_mobil_path(@mobil) %> |
<%= link_to 'Back', mobils_path %>