config/routes.rb
Rails.application.routes.draw do
  resources :antrians
  resources :pesans do
  	resources :bls
  end
  resources :diskus do
  	resources :komentars
  end

  resources :diskusis do
  	resources :commentds
  end
  resources :mobils
  resources :orangs
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'orangs#index'

  # ----- add these lines here: -----

	# Add a root route if you don't have one...
	# We can use users#new for now, or replace this with the controller and action you want to be the site root:
	root to: 'users#new'
  	
  	# sign up page with form:
	get 'users/new' => 'users#new', as: :new_user
	
	# create (post) action for when sign up form is submitted:
	post 'users' => 'users#create'

  	# ----- end of added lines -----

  	# ----- add these lines here: -----
	
	# log in page with form:
	get '/login'     => 'sessions#new'
	
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	
	# delete action to log out:
	delete '/logout' => 'sessions#destroy'  
  	
  	# ----- end of added lines -----

  # ----- add these lines here: -----

  # Add a root route if you don't have one...
  # We can use users#new for now, or replace this with the controller and action you want to be the site root:
  #root to: 'users#new'
    
    # sign up page with form:
  get 'bebeks/new' => 'bebeks#new', as: :new_bebek
  
  # create (post) action for when sign up form is submitted:
  post 'bebeks' => 'bebeks#create'

    # ----- end of added lines -----
    # ----- add these lines here: -----
  
  # log in page with form:
  get '/lbebek'     => 'lbebeks#new'
  
  # create (post) action for when log in form is submitted:
  post '/lbebek'    => 'lbebeks#create'
  
  # delete action to log out:
  delete '/logout' => 'lbebeks#destroy'  
    
    # ----- end of added lines -----


end

app/models/antrian.rb
class Antrian < ApplicationRecord
  belongs_to :orang
  belongs_to :user
end

app/models/bala.rb
class Bala < ApplicationRecord
  belongs_to :pesan
end

app/models/bebek.rb
class Bebek < ApplicationRecord
	# ----- add these lines here: -----
	
	#has_secure_password

	# Verify that email field is not blank and that it doesn't already exist in the db (prevents duplicates):
	validates :email, presence: true, uniqueness: true
	
	# ----- end of added lines -----
end

app/models/bl.rb
class Bl < ApplicationRecord
  belongs_to :pesan
end

app/models/commentd.rb
class Commentd < ApplicationRecord
  belongs_to :diskusi
end

app/models/commentdi.rb
class Commentdi < ApplicationRecord
  belongs_to :diskusi
end

app/models/disku.rb
class Disku < ApplicationRecord
  belongs_to :orang
  has_many :komentars
end

app/models/diskusi.rb
class Diskusi < ApplicationRecord
  belongs_to :orangs
  has_many :commentds
end

app/models/komentar.rb
class Komentar < ApplicationRecord
  belongs_to :disku
end

app/models/mobil.rb
class Mobil < ApplicationRecord
  belongs_to :orang
end

app/models/orang.rb
class Orang < ApplicationRecord
# has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
#   validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
has_attached_file :image, :styles => { :small => "150x150>" },
                  :url  => "/assets/orangs/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/orangs/:id/:style/:basename.:extension"

validates_attachment_presence :image
validates_attachment_size :image, :less_than => 5.megabytes
validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
end

app/models/pesan.rb
class Pesan < ApplicationRecord
  belongs_to :orang
  belongs_to :user
  has_many :bls
end

app/models/user.rb
class User < ApplicationRecord
	# ----- add these lines here: -----
	
	has_secure_password

	# Verify that email field is not blank and that it doesn't already exist in the db (prevents duplicates):
	validates :email, presence: true, uniqueness: true
	
	# ----- end of added lines -----
end

app/controllers/orangs_controller.rb
class OrangsController < ApplicationController
  before_action :set_orang, only: [:show, :edit, :update, :destroy]

  # GET /orangs
  # GET /orangs.json
  def index
    @orangs = Orang.all
  end

  # GET /orangs/1
  # GET /orangs/1.json
  def show
  end

  # GET /orangs/new
  def new
    @orang = Orang.new
  end

  # GET /orangs/1/edit
  def edit
  end

  # POST /orangs
  # POST /orangs.json
  def create
    @orang = Orang.new(orang_params)

    respond_to do |format|
      if @orang.save
        format.html { redirect_to @orang, notice: 'Orang was successfully created.' }
        format.json { render :show, status: :created, location: @orang }
      else
        format.html { render :new }
        format.json { render json: @orang.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orangs/1
  # PATCH/PUT /orangs/1.json
  def update
    respond_to do |format|
      if @orang.update(orang_params)
        format.html { redirect_to @orang, notice: 'Orang was successfully updated.' }
        format.json { render :show, status: :ok, location: @orang }
      else
        format.html { render :edit }
        format.json { render json: @orang.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orangs/1
  # DELETE /orangs/1.json
  def destroy
    @orang.destroy
    respond_to do |format|
      format.html { redirect_to orangs_url, notice: 'Orang was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orang
      @orang = Orang.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orang_params
      params.require(:orang).permit(:nama, :alamat, :jk, :foto ,:image)
    end
end

app/helpers/bebeks_helper.rb
module BebeksHelper
end

app/helpers/bls_helper.rb
module BlsHelper
end

app/helpers/diskus_helper.rb
module DiskusHelper
end

app/helpers/lbebeks_helper.rb
module LbebeksHelper
end

app/helpers/mobils_helper.rb
module MobilsHelper
end

app/helpers/orangs_helper.rb
module OrangsHelper
end

app/helpers/pesans_helper.rb
module PesansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/orangs/_form.html.erb
<%= form_with(model: orang, local: true , :html => { :multipart => true }) do |form| %>

  <% if orang.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orang.errors.count, "error") %> prohibited this orang from being saved:</h2>

      <ul>
      <% orang.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nama %>
    <%= form.text_field :nama %>
  </div>

  <div class="field">
    <%= form.label :alamat %>
    <%= form.text_field :alamat %>
  </div>

  <div class="field">
    <%= form.label :jk %>
    <%= form.text_field :jk %>
  </div>

  <div class="field">
    <%= form.label :foto %>
   <%= form.text_field :foto %>
  </div>

    <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>


  <div class="actions">
    <%= form.submit "Simpan" %>
  </div>
<% end %>

app/views/orangs/edit.html.erb
<h1>Editing Orang</h1>

<%= render 'form', orang: @orang %>

<%= link_to 'Show', @orang %> |
<%= link_to 'Back', orangs_path %>

app/views/orangs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orangs</h1>
<%#= current_user.id %>

<table>
  <thead>
    <tr>
      <th>Nama</th>
      <th>Alamat</th>
      <th>Jk</th>
      <th>Foto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orangs.each do |orang| %>
 
      <tr>
        <td><%= orang.nama %></td>
        <td><%= orang.alamat %></td>
        <td><%= orang.jk %></td>
        <td><%= orang.foto %></td>
        <td><%= link_to 'Show', orang %></td>
        <td><%= link_to 'Edit', edit_orang_path(orang) %></td>
        <td><%= link_to 'Destroy', orang, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orang', new_orang_path %>

app/views/orangs/new.html.erb
<h1>New Orang</h1>

<%= render 'form', orang: @orang %>

<%= link_to 'Back', orangs_path %>

app/views/orangs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama:</strong>
  <%= @orang.nama %>
</p>

<p>
  <strong>Alamat:</strong>
  <%= @orang.alamat %>
</p>

<p>
  <strong>Jk:</strong>
  <%= @orang.jk %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @orang.foto %>
</p>

<p>
  <strong>image:</strong>
  <%= image_tag @orang.image.url(:small) %>
</p>

<%= link_to 'Edit', edit_orang_path(@orang) %> |
<%= link_to 'Back', orangs_path %>