config/routes.rb
Rails.application.routes.draw do
  resources :antrians
  resources :pesans do
  	resources :bls
  end
  resources :diskus do
  	resources :komentars
  end

  resources :diskusis do
  	resources :commentds
  end
  resources :mobils
  resources :orangs
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'orangs#index'

  # ----- add these lines here: -----

	# Add a root route if you don't have one...
	# We can use users#new for now, or replace this with the controller and action you want to be the site root:
	root to: 'users#new'
  	
  	# sign up page with form:
	get 'users/new' => 'users#new', as: :new_user
	
	# create (post) action for when sign up form is submitted:
	post 'users' => 'users#create'

  	# ----- end of added lines -----

  	# ----- add these lines here: -----
	
	# log in page with form:
	get '/login'     => 'sessions#new'
	
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	
	# delete action to log out:
	delete '/logout' => 'sessions#destroy'  
  	
  	# ----- end of added lines -----

  # ----- add these lines here: -----

  # Add a root route if you don't have one...
  # We can use users#new for now, or replace this with the controller and action you want to be the site root:
  #root to: 'users#new'
    
    # sign up page with form:
  get 'bebeks/new' => 'bebeks#new', as: :new_bebek
  
  # create (post) action for when sign up form is submitted:
  post 'bebeks' => 'bebeks#create'

    # ----- end of added lines -----
    # ----- add these lines here: -----
  
  # log in page with form:
  get '/lbebek'     => 'lbebeks#new'
  
  # create (post) action for when log in form is submitted:
  post '/lbebek'    => 'lbebeks#create'
  
  # delete action to log out:
  delete '/logout' => 'lbebeks#destroy'  
    
    # ----- end of added lines -----


end

app/models/antrian.rb
class Antrian < ApplicationRecord
  belongs_to :orang
  belongs_to :user
end

app/models/bala.rb
class Bala < ApplicationRecord
  belongs_to :pesan
end

app/models/bebek.rb
class Bebek < ApplicationRecord
	# ----- add these lines here: -----
	
	#has_secure_password

	# Verify that email field is not blank and that it doesn't already exist in the db (prevents duplicates):
	validates :email, presence: true, uniqueness: true
	
	# ----- end of added lines -----
end

app/models/bl.rb
class Bl < ApplicationRecord
  belongs_to :pesan
end

app/models/commentd.rb
class Commentd < ApplicationRecord
  belongs_to :diskusi
end

app/models/commentdi.rb
class Commentdi < ApplicationRecord
  belongs_to :diskusi
end

app/models/disku.rb
class Disku < ApplicationRecord
  belongs_to :orang
  has_many :komentars
end

app/models/diskusi.rb
class Diskusi < ApplicationRecord
  belongs_to :orangs
  has_many :commentds
end

app/models/komentar.rb
class Komentar < ApplicationRecord
  belongs_to :disku
end

app/models/mobil.rb
class Mobil < ApplicationRecord
  belongs_to :orang
end

app/models/orang.rb
class Orang < ApplicationRecord
# has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
#   validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
has_attached_file :image, :styles => { :small => "150x150>" },
                  :url  => "/assets/orangs/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/orangs/:id/:style/:basename.:extension"

validates_attachment_presence :image
validates_attachment_size :image, :less_than => 5.megabytes
validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
end

app/models/pesan.rb
class Pesan < ApplicationRecord
  belongs_to :orang
  belongs_to :user
  has_many :bls
end

app/models/user.rb
class User < ApplicationRecord
	# ----- add these lines here: -----
	
	has_secure_password

	# Verify that email field is not blank and that it doesn't already exist in the db (prevents duplicates):
	validates :email, presence: true, uniqueness: true
	
	# ----- end of added lines -----
end

app/controllers/diskusis_controller.rb
class DiskusisController < ApplicationController
  before_action :set_diskusi, only: [:show, :edit, :update, :destroy]

  # GET /diskusis
  # GET /diskusis.json
  def index
    @diskusis = Diskusi.all
  end

  # GET /diskusis/1
  # GET /diskusis/1.json
  def show
  end

  # GET /diskusis/new
  def new
    @diskusi = Diskusi.new
  end

  # GET /diskusis/1/edit
  def edit
  end

  # POST /diskusis
  # POST /diskusis.json
  def create
    @diskusi = Diskusi.new(diskusi_params)

    respond_to do |format|
      if @diskusi.save
        format.html { redirect_to @diskusi, notice: 'Diskusi was successfully created.' }
        format.json { render :show, status: :created, location: @diskusi }
      else
        format.html { render :new }
        format.json { render json: @diskusi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diskusis/1
  # PATCH/PUT /diskusis/1.json
  def update
    respond_to do |format|
      if @diskusi.update(diskusi_params)
        format.html { redirect_to @diskusi, notice: 'Diskusi was successfully updated.' }
        format.json { render :show, status: :ok, location: @diskusi }
      else
        format.html { render :edit }
        format.json { render json: @diskusi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diskusis/1
  # DELETE /diskusis/1.json
  def destroy
    @diskusi.destroy
    respond_to do |format|
      format.html { redirect_to diskusis_url, notice: 'Diskusi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diskusi
      @diskusi = Diskusi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diskusi_params
      params.require(:diskusi).permit(:isi, :tgl, :orangs_id)
    end
end

app/helpers/bebeks_helper.rb
module BebeksHelper
end

app/helpers/bls_helper.rb
module BlsHelper
end

app/helpers/diskus_helper.rb
module DiskusHelper
end

app/helpers/diskusis_helper.rb
module DiskusisHelper
end

app/helpers/lbebeks_helper.rb
module LbebeksHelper
end

app/helpers/mobils_helper.rb
module MobilsHelper
end

app/helpers/orangs_helper.rb
module OrangsHelper
end

app/helpers/pesans_helper.rb
module PesansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diskusis/_form.html.erb
<%= form_with(model: diskusi, local: true) do |form| %>
  <% if diskusi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diskusi.errors.count, "error") %> prohibited this diskusi from being saved:</h2>

      <ul>
      <% diskusi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :isi %>
    <%= form.text_area :isi %>
  </div>

  <div class="field">
    <%= form.label :tgl %>
    <%= form.date_select :tgl %>
  </div>

  <div class="field">
    <%= form.label :orangs_id %>
    <%= form.text_field :orangs_id , :value => current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/diskusis/edit.html.erb
<h1>Editing Diskusi</h1>

<%= render 'form', diskusi: @diskusi %>

<%= link_to 'Show', @diskusi %> |
<%= link_to 'Back', diskusis_path %>

app/views/diskusis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Diskusis</h1>

<table>
  <thead>
    <tr>
      <th>Isi</th>
      <th>Tgl</th>
      <th>Orangs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diskusis.each do |diskusi| %>
      <tr>
        <td><%= diskusi.isi %></td>
        <td><%= diskusi.tgl %></td>
        <td><%= diskusi.orangs %></td>
        <td><%= link_to 'Show', diskusi %></td>
        <td><%= link_to 'Edit', edit_diskusi_path(diskusi) %></td>
        <td><%= link_to 'Destroy', diskusi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diskusi', new_diskusi_path %>

app/views/diskusis/new.html.erb
<h1>New Diskusi</h1>

<%= render 'form', diskusi: @diskusi %>

<%= link_to 'Back', diskusis_path %>

app/views/diskusis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Isi:</strong>
  <%= @diskusi.isi %>
</p>

<p>
  <strong>Tgl:</strong>
  <%= @diskusi.tgl %>
</p>

<p>
  <strong>Orangs:</strong>
  <%= @diskusi.orangs %>
</p>

<h2>Add a comment:</h2>
<%= form_with(model: [ @diskusi, @diskusi.commentds.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :isi %><br>
    <%= form.text_area :isi %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_diskusi_path(@diskusi) %> |
<%= link_to 'Back', diskusis_path %>