config/routes.rb
Rails.application.routes.draw do
  resources :antrians
  resources :pesans do
  	resources :bls
  end
  resources :diskus do
  	resources :komentars
  end

  resources :diskusis do
  	resources :commentds
  end
  resources :mobils
  resources :orangs
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'orangs#index'

  # ----- add these lines here: -----

	# Add a root route if you don't have one...
	# We can use users#new for now, or replace this with the controller and action you want to be the site root:
	root to: 'users#new'
  	
  	# sign up page with form:
	get 'users/new' => 'users#new', as: :new_user
	
	# create (post) action for when sign up form is submitted:
	post 'users' => 'users#create'

  	# ----- end of added lines -----

  	# ----- add these lines here: -----
	
	# log in page with form:
	get '/login'     => 'sessions#new'
	
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	
	# delete action to log out:
	delete '/logout' => 'sessions#destroy'  
  	
  	# ----- end of added lines -----

  # ----- add these lines here: -----

  # Add a root route if you don't have one...
  # We can use users#new for now, or replace this with the controller and action you want to be the site root:
  #root to: 'users#new'
    
    # sign up page with form:
  get 'bebeks/new' => 'bebeks#new', as: :new_bebek
  
  # create (post) action for when sign up form is submitted:
  post 'bebeks' => 'bebeks#create'

    # ----- end of added lines -----
    # ----- add these lines here: -----
  
  # log in page with form:
  get '/lbebek'     => 'lbebeks#new'
  
  # create (post) action for when log in form is submitted:
  post '/lbebek'    => 'lbebeks#create'
  
  # delete action to log out:
  delete '/logout' => 'lbebeks#destroy'  
    
    # ----- end of added lines -----


end

app/models/antrian.rb
class Antrian < ApplicationRecord
  belongs_to :orang
  belongs_to :user
end

app/models/bala.rb
class Bala < ApplicationRecord
  belongs_to :pesan
end

app/models/bebek.rb
class Bebek < ApplicationRecord
	# ----- add these lines here: -----
	
	#has_secure_password

	# Verify that email field is not blank and that it doesn't already exist in the db (prevents duplicates):
	validates :email, presence: true, uniqueness: true
	
	# ----- end of added lines -----
end

app/models/bl.rb
class Bl < ApplicationRecord
  belongs_to :pesan
end

app/models/commentd.rb
class Commentd < ApplicationRecord
  belongs_to :diskusi
end

app/models/commentdi.rb
class Commentdi < ApplicationRecord
  belongs_to :diskusi
end

app/models/disku.rb
class Disku < ApplicationRecord
  belongs_to :orang
  has_many :komentars
end

app/models/diskusi.rb
class Diskusi < ApplicationRecord
  belongs_to :orangs
  has_many :commentds
end

app/models/komentar.rb
class Komentar < ApplicationRecord
  belongs_to :disku
end

app/models/mobil.rb
class Mobil < ApplicationRecord
  belongs_to :orang
end

app/models/orang.rb
class Orang < ApplicationRecord
# has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
#   validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
has_attached_file :image, :styles => { :small => "150x150>" },
                  :url  => "/assets/orangs/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/orangs/:id/:style/:basename.:extension"

validates_attachment_presence :image
validates_attachment_size :image, :less_than => 5.megabytes
validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
end

app/models/pesan.rb
class Pesan < ApplicationRecord
  belongs_to :orang
  belongs_to :user
  has_many :bls
end

app/models/user.rb
class User < ApplicationRecord
	# ----- add these lines here: -----
	
	has_secure_password

	# Verify that email field is not blank and that it doesn't already exist in the db (prevents duplicates):
	validates :email, presence: true, uniqueness: true
	
	# ----- end of added lines -----
end

app/controllers/pesans_controller.rb
class PesansController < ApplicationController
  before_action :set_pesan, only: [:show, :edit, :update, :destroy]

  # GET /pesans
  # GET /pesans.json
  def index
    @pesans = Pesan.all
  end

  # GET /pesans/1
  # GET /pesans/1.json
  def show
  end

  # GET /pesans/new
  def new
    @pesan = Pesan.new
  end

  # GET /pesans/1/edit
  def edit
  end

  # POST /pesans
  # POST /pesans.json
  def create
    @pesan = Pesan.new(pesan_params)

    respond_to do |format|
      if @pesan.save
        format.html { redirect_to @pesan, notice: 'Pesan was successfully created.' }
        format.json { render :show, status: :created, location: @pesan }
      else
        format.html { render :new }
        format.json { render json: @pesan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pesans/1
  # PATCH/PUT /pesans/1.json
  def update
    respond_to do |format|
      if @pesan.update(pesan_params)
        format.html { redirect_to @pesan, notice: 'Pesan was successfully updated.' }
        format.json { render :show, status: :ok, location: @pesan }
      else
        format.html { render :edit }
        format.json { render json: @pesan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pesans/1
  # DELETE /pesans/1.json
  def destroy
    @pesan.destroy
    respond_to do |format|
      format.html { redirect_to pesans_url, notice: 'Pesan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pesan
      @pesan = Pesan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pesan_params
      params.require(:pesan).permit(:isi, :orang_id, :user_id)
    end
end

app/helpers/bebeks_helper.rb
module BebeksHelper
end

app/helpers/bls_helper.rb
module BlsHelper
end

app/helpers/diskus_helper.rb
module DiskusHelper
end

app/helpers/lbebeks_helper.rb
module LbebeksHelper
end

app/helpers/mobils_helper.rb
module MobilsHelper
end

app/helpers/orangs_helper.rb
module OrangsHelper
end

app/helpers/pesans_helper.rb
module PesansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/pesans/_form.html.erb
<%= form_with(model: pesan, local: true) do |form| %>
  <% if pesan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pesan.errors.count, "error") %> prohibited this pesan from being saved:</h2>

      <ul>
      <% pesan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :isi %>
    <%= form.text_field :isi %>
  </div>

  <div class="field">
    <%= form.label :Dari %>
    <%= form.text_field :orang_id %>
  </div>

  <div class="field">
    <%= form.label :Kepada %>
    <%= form.text_field :user_id %>
  </div>
<%= current_user.id %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pesans/edit.html.erb
<h1>Editing Pesan</h1>

<%= render 'form', pesan: @pesan %>

<%= link_to 'Show', @pesan %> |
<%= link_to 'Back', pesans_path %>

app/views/pesans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pesans</h1>

<table>
  <thead>
    <tr>
      <th>Isi</th>
      <th>Dari</th>
      <th>Kepada</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pesans.each do |pesan| %>
      <tr>
        <td><%= pesan.isi %></td>
        <td><%= pesan.orang.nama %></td>
        <td><%= pesan.user.email %></td>
        <td><%= link_to 'Show', pesan %></td>
        <td><%= link_to 'Edit', edit_pesan_path(pesan) %></td>
        <td><%= link_to 'Destroy', pesan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pesan', new_pesan_path %>

app/views/pesans/new.html.erb
<h1>New Pesan</h1>

<%= render 'form', pesan: @pesan %>

<%= link_to 'Back', pesans_path %>

app/views/pesans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pesan</strong>
  <br>
  <b><%= @pesan.orang.nama %> </b> : <%= @pesan.isi %>
</p>
<% @pesan.bls.each do |comment| %>
  <p>
    <strong><%= comment.org %></strong>
  	<%= comment.isi %>
  </p>
 
    
<% end %>
<h2>Add a comment:</h2>
<%= form_with(model: [ @pesan, @pesan.bls.build ], local: true) do |form| %>
  <p>
    <%= form.label :org %><br>
    <%= form.text_field :org , :value => current_user.name %>
  </p>
  <p>
    <%= form.label :isi %><br>
    <%= form.text_area :isi %>
  </p>
  <p>
    <%= form.submit "Balas" %>
  </p>
<% end %>

<!-- <p>
  <strong>Kepada:</strong>
  <%= @pesan.user.name %>
</p> -->

<%#= link_to 'Edit', edit_pesan_path(@pesan) %> 
<%= link_to 'Kembali', pesans_path %>